### PR TITLE
Fixed tutorial to point to the correct template

### PR DESCRIPTION
**Pull request by macolso**
Content must go through a pre-merge checklist.

## Pre-Merge Content Checklist

This documentation has been checked to ensure that:

- [x] The `title, `template`, and `date` are all set
- [x] File does not use CRLF, but uses plain LF (hint: use `cat -ve <filename> | grep '^M' | wc -l` and expect 0 as a result) 
- [x] Has passed [`bart check`](https://bartholomew.fermyon.dev/quickstart)
- [x] Has run `npm run build-index`
- [x] Has been manually tested by running in Spin/Bartholomew (hint: use `PREVIEW_MODE=1` and run `npm run styles` to update styling)
- [x] Headings are using Title Case
- [x] Code blocks have the programming language set to properly highlight syntax and the proper copy directive
- [x] Have tested with `npm run test` and resolved all errors

### CODE REVIEW

**Comment by macolso** [comment]
tagging @kate-goldenring for viz :)

**Comment by rajatjindal** [comment]
Hi @macolso 

i think this tutorial is suppose to  use `redis-rust` template.

**Comment by macolso** [comment]
I walked through this yesterday using the `redis rust` template, and ran into issues. After chatting with Kate, I learned `redis-*` templates [aren't supported on cloud yet](https://github.com/fermyon/developer/issues/90#issuecomment-1281858366).

**Comment by kate-goldenring** [comment]
> Hi @macolso
> 
> i think this tutorial is suppose to use `redis-rust` template.
> 
> we should probably change references of `http-rust` to `redis-rust` :)

@rajatjindal the distinction here is that this example is for outbound redis. We don't support the redis trigger on Fermyon Cloud (https://github.com/fermyon/developer/issues/90#issuecomment-1281858366) -- right now, apps cannot be triggered by redis events; however, they can publish messages to redis. This was an error in the docs to install the `redis-rust` template instead of `http-rust`. This is probably something we could make clearer in the docs writeup -- why we are using http component for something redis related. Maybe a note.

**Comment by macolso** [comment]
I really liked Ivan's suggestion in [#90](https://github.com/fermyon/developer/issues/90) to create a conceptual article that elaborates on templates and trigger as well as their relationship. Maybe this is something I can work on with @melissaklein24.

**Pull request merged**
