### PR TITLE
Accordion menus

### PR DESCRIPTION
**Pull request by karthik2804**
Adds accordion menu

image

### CODE REVIEW

**Comment by flynnduism** [comment]
I have two comments -

* Collapse behavior (JS)
One when you open a section, it seems to collapse another.  I don't see a good reason for this as I think it makes it harder to find a page when you're browsing from section to section

*  Vague categories should be avoided (content)
I noticed a section called Advanced which has all sorts of different things mixed in.  This seems like it will make it hard to find the pages in here naturally. If things don't have a logical grouping, can we just ungroup them? (have a mix of accordion and non-accordion links)

**Comment by karthik2804** [comment]
Happy to remove the animation and also restructure stuff as we see fit. We could definitely have a mixture.

**Comment by itowlson** [comment]
Related to the auto collapse: this has the odd effect that if you are on a page in Section A, and expand Section B, your current page is no longer highlighted (or even visible) in the TOC.  So maybe another reason to remove the auto-collapse.

On the other hand I can see after someone has visited a few pages it could leave them with half the groups open and effectively back to a super long TOC.  Not sure what the compromise is.

**Comment by itowlson** [comment]
@flynnduism The trouble with breaking the rag-bag of "advanced" topics up to top level is that it makes the most esoteric topics the most visible.  99.7% of users don't need to know how to author a template or how the registry cache is laid out: those shouldn't be the few pages that are always there asking to be clicked on.

We can for sure try to break out themes or move pages to other groups.  But there's a good chance we'll always be left with a few "look this is something we need to write down for the few niche users who care about it but it doesn't really relate to much else" kind of pages.  I'm not too uncomfortable with an "Advanced" or "Other Topics" kind of dumping area for those.  But yes we could always be more disciplined about using it!

**Comment by itowlson** [comment]
Wow, I'm sorry @karthik2804, I went straight to the one thing that niggled me.  I really like this.  It looks good and definitely helps keep things tidy.  And that should have been my main message!

**Comment by karthik2804** [comment]
@itowlson i appreciate the feedback. One potential solution is to have the currently active section always be open while closing the rest when browsing. It should be straightforward to implement that.

**Review by itowlson — APPROVED** [review]
Thanks for the update.  If @flynnduism is happy then I am happy.  We can keep iterating on this as we (and, more importantly, users) try it in practice.

**Review by tpmccallum — APPROVED** [review]

**Review by itowlson — APPROVED** [review]
Looks good!  My only niggle is that if I close the Get Started section (because I am now the SPIN MASTER) and then visit a new page, it pops open again.  But happy to iterate on that in post.

image

**Comment by karthik2804** [comment]
Oooh, @itowlson nice catch! That is an easy fix. Fix on its way.

**Pull request merged**
