### PR TITLE
[WIP] Add Kubernetes Scenario docs

### PR DESCRIPTION
**Pull request by voigt**
Content must go through a pre-merge checklist.

## Pre-Merge Content Checklist

This documentation has been checked to ensure that:

- [X] The `title, `template`, and `date` are all set
- [X] Does this PR have a new menu item (anywhere in `templates/*.hbs` files) that points to a document `.md` that is set to publish in the future? If so please only publish the `.md` and `.hbs` changes in real-time (otherwise there will be a menu item pointing to a `.md` file that does not exist)
- [X] File does not use CRLF, but uses plain LF (hint: use `cat -ve <filename> | grep '^M' | wc -l` and expect 0 as a result) 
- [X] Has passed [`bart check`](https://developer.fermyon.com/bartholomew/quickstart)
- [X] Has been manually tested by running in Spin/Bartholomew (hint: use `PREVIEW_MODE=1` and run `npm run styles` to update styling)
- [X] Headings are using Title Case
- [X] Code blocks have the programming language set to properly highlight syntax and the proper copy directive
- [X] Have tested with `npm run test` and resolved all errors
- [X] Relates to an existing (potentially outdated) blog article? If so please add URL in blog to point to this content.

### CODE REVIEW

**Comment by tpmccallum** [comment]
Thanks for this @voigt 
I will take a look and do some testing on this today; hopefully, we can get this merged soon.
Thanks again for this excellent contribution.
It looks like some action is required with the DCO, can you please take a look at this link Re: signing
https://github.com/fermyon/developer/pull/1070/checks?check_run_id=19293707490

**Comment by voigt** [comment]
Hey @tpmccallum thank you for taking care.

Re DCO: I squashed my commits and fixed the issue.

I furthermore added some adjustments to the dynamic application configuration chapter.

There is one styling related issue that bothers me: the Chapter "Spin on Kubernetes" always appears to be active. I couldn't find the issue on my own - maybe you have an idea?

CleanShot 2023-12-05 at 14 55 28

**Comment by karthik2804** [comment]
@voigt The issue is due to a `rhai` script. I can fix that in a follow up PR. More context on the issue is that we are currently seeing if the link URL is a part of the `window.location` and the URL for `Spin on kubernetes` is a substring of the URL for `Dynamic Application Configuration on Kubernetes` thus both seem to be active. 

Switching the `rhai` script to match the entire string as a suffix instead of checking to see if it contains the substring should solve the issue.

**Review by tpmccallum — APPROVED** [review]
Thanks @voigt

**Pull request merged**
