### PR TITLE
docs(http-trigger.md): link rendering fixes and minor updates

### PR DESCRIPTION
**Pull request by vdice**
- Fixes issue where some links weren't clickable (perhaps because there was a trailing `.` or `:`?)  Please advise if there is a preferred approach to having them render correctly.
- Add'l minor fixes/updates

Before:
hyperlinks-broke

After:
hyperlinks-fixed

Content must go through a pre-merge checklist.

## Pre-Merge Content Checklist

This documentation has been checked to ensure that:

- [ ] The `title, `template`, and `date` are all set
- [ ] Does this PR have a new menu item (anywhere in `templates/*.hbs` files) that points to a document `.md` that is set to publish in the future? If so please only publish the `.md` and `.hbs` changes in real-time (otherwise there will be a menu item pointing to a `.md` file that does not exist)
- [x] File does not use CRLF, but uses plain LF (hint: use `cat -ve <filename> | grep '^M' | wc -l` and expect 0 as a result) 
- [x] Has passed [`bart check`](https://developer.fermyon.com/bartholomew/quickstart)
- [x] Has run `npm run build-index`
- [x] Has been manually tested by running in Spin/Bartholomew (hint: use `PREVIEW_MODE=1` and run `npm run styles` to update styling)
- [ ] Headings are using Title Case
- [ ] Code blocks have the programming language set to properly highlight syntax and the proper copy directive
- [ ] Have tested with `npm run test` and resolved all errors

### CODE REVIEW

**Review by karthik2804 — APPROVED** [review]

**Review by karthik2804 — APPROVED** [review]

**Comment by itowlson** [comment]
@karthik2804 is there a way to fix this in Bartholomew?  Trailing punctuation doesn't normally prevent auto-linking in other Markdown environments I've used...?

**Comment by karthik2804** [comment]
I am not sure that I follow. Do you mean syntax like `[example](www.example.com).` They do work as expected.

**Comment by vdice** [comment]
@karthik2804 I think @itowlson meant the way the links were before this fix.  They were raw, valid links eg `https://github.com/fermyon/spin/blob/main/wit/ephemeral.` but my theory was the hyperlink functionality broke when punctuation was involved, such as the `.` at the end there.  Bartholomew issue or maybe js logic issue for this website?

**Comment by karthik2804** [comment]
@vdice @itowlson, it makes sense now. It is due markdown parser we use. it does not auto-detect URLs even in cases of lack of punctuation. I can look into it further. But from a quick glance, it looks like the syntax for the raw URL is `<URL_HERE>` that is the URL is enclosed in angled brackets.

**Pull request merged**
