### PR TITLE
Update GitHub page url in frontmatter

### PR DESCRIPTION
**Pull request by tpmccallum**
Signed-off-by: tpmccallum tim.mccallum@fermyon.com

### CODE REVIEW

**Review by itowlson — APPROVED** [review]

**Comment by itowlson** [comment]
Should these be getting picked up by the link checker?  Not a big deal, just curious.

**Comment by sohanmaheshwar** [comment]
LGTM

**Comment by karthik2804** [comment]
>Should these be getting picked up by the link checker? Not a big deal, just curious.

not a broken link, it just redirects transparently to `v2/`

**Comment by itowlson** [comment]
@karthik2804 It's not redirecting for me. I don't see how GitHub would know to do so.

**Comment by karthik2804** [comment]
Oh sorry I thought it was a url on the website not GitHub itself.

**Pull request merged**
