### PR TITLE
fixing the key value tutorial urls in the md files

### PR DESCRIPTION
**Pull request by vcs222**
fixing the key value tutorial urls in the md files for both v1 and v2 md docs

### CODE REVIEW

**Review by radu-matei — APPROVED** [review]
Thank you for your contribution, @vcs222!

Would you mind signing your commit, please? (https://developer.fermyon.com/spin/v2/contributing-docs#9-commit-changes)
Thanks!

**Comment by tpmccallum** [comment]
Thanks so much, @vcs222 - please let us know if you need anything regarding signing the commit.
Thanks for the contribution, it is greatly appreciated; once signed, we can get this merged.

**Comment by vcs222** [comment]
@radu-matei @tpmccallum 
Sorry for missing the signing, it should be good now.
I am happy to contribute ;)

**Comment by tpmccallum** [comment]
Thanks for the contribution @vcs222 - greatly appreciated!

**Pull request merged**
