### PR TITLE
fix sitemap to point at preview pages instead of api

### PR DESCRIPTION
**Pull request by karthik2804**

### CODE REVIEW

**Comment by flynnduism** [comment]
LGTM, but would wait to see what @tpmccallum thinks before shipping

**Comment by tpmccallum** [comment]
Thanks @karthik2804 
Good spotting.
I wondered if it would be better to redirect at the `spin.toml` level so that the sitemap naturally renders the correct URLs.
Is it technically possible to implement a `path_prefix` redirect in the manifest?

**Review by tpmccallum — APPROVED** [review]
Thanks so much @karthik2804

**Comment by tpmccallum** [comment]
Just double-checked it locally. Looks great!
Thanks again @karthik2804 
Screenshot 2023-11-27 at 10 54 40

**Pull request merged**
