### PR TITLE
Update broken links on quickstart page

### PR DESCRIPTION
**Pull request by tpmccallum**
Signed-off-by: tpmccallum tim.mccallum@fermyon.com

### CODE REVIEW

**Review by itowlson — APPROVED** [review]
I would like to leave the issue open to prompt us to investigate.  We don't know why these work locally, or if any other links on the site are broken; we need to understand as well as emergency patching.  (But yes emergency patch for now!)

**Comment by karthik2804** [comment]
I have it figured out. If there is a trailing `/`, the link is broken.

**Review by itowlson — CHANGES_REQUESTED** [review]
From what @karthik2804 has found we need to solve the problem elsewhere

**Comment by itowlson** [comment]
@tpmccallum Sorry for leaving a request changes - there is no point papering over these two specific links when the issue is global and could hit any page that has the slashy link, so I wanted to put this on hold while we figure it out.

**Comment by karthik2804** [comment]
The only places with trailing slashes are in the search box.  We should possibly not be using those relative URLs given any external website can link that way as well. 

https://github.com/fermyon/developer/blob/1754705721cca42749482642411b40ccf4bedecf/static/js/src/modules/search.js#L179


image

**Comment by itowlson** [comment]
Can we fix this in Bartholomew @karthik2804 or do we need to work around it by authoring absolute links from now on?

**Comment by karthik2804** [comment]
The only way it can be fixed in Bartholomew is to translate the relative URLs to absolute URLs. I would have to look into that a little bit before I can confirm. But yes that should be possible.

**Comment by tpmccallum** [comment]
In reference to the above comment, https://github.com/fermyon/developer/pull/482#issuecomment-1473110820, this will be close in lieu of another different approach to fix.

**Pull request closed without merging**
