### PR TITLE
Add border to images to distinguish between background and images

### PR DESCRIPTION
**Pull request by karthik2804**
Before 
image

After
image

Bonus content (light mode)
image

PS: @flynnduism is a CSS wizard!

### CODE REVIEW

**Comment by itowlson** [comment]
On what images does this appear?  (Like we wouldn't want it around the Fermyon logo for example.)

**Comment by karthik2804** [comment]
Good catch - I will scope it down to be safer. It did not break the Fermyon logo but broke the project cards. I have scoped it down now to only have borders on images inside the body of doc pages.

**Comment by tpmccallum** [comment]
This looks good.
Nice work.
One thing though, remember yesterday how the text colour on the Spin, Cloud and Bartholomew project boxes was all of a sudden incorrect? Same thing is happening again.

image

**Comment by karthik2804** [comment]
That is because i did not create this branch from `main`. it should be fine once we merge to main.

**Comment by karthik2804** [comment]
I can rebase if that would be preferred to be sure.

**Comment by tpmccallum** [comment]
I guess we better check, so re base would be ideal if possible (so I can preview locally)

**Comment by karthik2804** [comment]
@tpmccallum rebased!

**Comment by tpmccallum** [comment]
Thanks, checking now.

**Review by tpmccallum — APPROVED** [review]
Looks really great, thanks @karthik2804

**Pull request merged**
