### PR TITLE
docs(wasm-languages): rust updates

### PR DESCRIPTION
**Pull request by vdice**
Mostly focused on updating the example app code/spin.toml, similar to https://github.com/fermyon/developer/pull/1403

### CODE REVIEW

**Comment by vdice** [comment]
I'm tempted to completely remove WAGI-related mentions like https://github.com/fermyon/developer/blob/bd5326db3295ac06d54f0ff4c7b902670fe4e85f/content/wasm-languages/rust.md?plain=1#L59, https://github.com/fermyon/developer/blob/bd5326db3295ac06d54f0ff4c7b902670fe4e85f/content/wasm-languages/rust.md?plain=1#L128-L130 and https://github.com/fermyon/developer/blob/bd5326db3295ac06d54f0ff4c7b902670fe4e85f/content/wasm-languages/rust.md?plain=1#L141.  Thoughts?

**Review by itowlson — APPROVED** [review]
Yikes this was ancient.  Thanks

**Comment by itowlson** [comment]
I'm okay with removing the WAGI mentions.  Do you want me to hold off on merging this PR, or do you envisage deferring those to a separate PR?

**Comment by vdice** [comment]
> I'm okay with removing the WAGI mentions. Do you want me to hold off on merging this PR, or do you envisage deferring those to a separate PR?

👍 I'll push the changes in this PR.

**Comment by vdice** [comment]
@itowlson most wagi mentions removed in https://github.com/fermyon/developer/pull/1404/commits/ef8aec635da371717b98f37ad9d7a4680eac045f

**Review by itowlson — APPROVED** [review]

**Pull request merged**
