### PR TITLE
Upgrade of Bartholomew Wasm Module

### PR DESCRIPTION
**Pull request by tpmccallum**
This is an update of the `bartholomew.wasm` file in the modules directory to implement fixes for relative vs absolute URLs and also improvements i.e. allowing dynamic URLs (so a user is not thrust over to the `common` section's menu if clicking on a shared document that exists in the common area).

### CODE REVIEW

**Comment by tpmccallum** [comment]
Closes https://github.com/fermyon/developer/issues/481

**Comment by tpmccallum** [comment]
Closes https://github.com/fermyon/developer/issues/603

Where an instance of localhost was being used for hyperlink to another page.

**Comment by tpmccallum** [comment]
Closes https://github.com/fermyon/developer/issues/617

**Comment by tpmccallum** [comment]
Closes https://github.com/fermyon/developer/issues/410

**Comment by tpmccallum** [comment]
Closes https://github.com/fermyon/developer/issues/394

**Review by itowlson — APPROVED** [review]
Yay!  Thank you @tpmccallum and @karthik2804!

**Pull request merged**
