### PR TITLE
ci(*): update publish/deploy to use ghcr.io; untrack static/data.json

### PR DESCRIPTION
**Pull request by vdice**
Updates publish/deploy logic to use an OCI registry (first choice: ghcr.io).  In doing so, we generate the search index (`static/data.json`) at time of publishing, removing the need to track in version control.  (Ref https://github.com/fermyon/developer/issues/369)

Placing in Draft for now as there is one blocker:  Getting errors attempting to push this Developer website Spin app to ghcr.io (see https://github.com/vdice/developer/actions/runs/4326339883/jobs/7553631989).  An auth error is produced which is odd/unexpected as I can publish other Spin apps to ghcr.io with the same flow.  Additionally, this Developer site can be published to docker.io/DockerHub.  Need to investigate.

_edit: Update on the blocker.  As mentioned, it only occurs with ghcr.io due to its auth token mechanism, which appears to only be valid for 1 minute and is used for all layer push requests.  This, in tandem with spin's sequential image layer pushes (and pulls) causes the timeout.  We are tracking updating spin to push and pull concurrently, which will benefit regardless of registry (see https://github.com/fermyon/spin/pull/1296) but should also unblock pushing to ghcr.io._

## Pre-Merge Content Checklist

This documentation has been checked to ensure that:

- [ ] The `title, `template`, and `date` are all set
- [ ] Does this PR have a new menu item (anywhere in `templates/*.hbs` files) that points to a document `.md` that is set to publish in the future? If so please only publish the `.md` and `.hbs` changes in real-time (otherwise there will be a menu item pointing to a `.md` file that does not exist)
- [ ] File does not use CRLF, but uses plain LF (hint: use `cat -ve <filename> | grep '^M' | wc -l` and expect 0 as a result) 
- [ ] Has passed [`bart check`](https://developer.fermyon.com/bartholomew/quickstart)
- [ ] Has run `npm run build-index`
- [ ] Has been manually tested by running in Spin/Bartholomew (hint: use `PREVIEW_MODE=1` and run `npm run styles` to update styling)
- [ ] Headings are using Title Case
- [ ] Code blocks have the programming language set to properly highlight syntax and the proper copy directive
- [ ] Have tested with `npm run test` and resolved all errors

### CODE REVIEW

**Comment by bacongobbler** [comment]
Does the action have write permissions to the package API? IIRC you need to add the following to your job metadata:

```
jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
```

https://docs.github.com/en/actions/publishing-packages/publishing-docker-images#publishing-images-to-github-packages

**Comment by karthik2804** [comment]
@bacongobbler I could reproduce this issue from my local CLI as well. I am able to push other packages but this one fails. So I am not entirely sure that it is a permissions issue.

**Comment by itowlson** [comment]
I see the same thing as @karthik2804 - from my local machine:

* I can push "hello world" applications to ghcr
* I can push the developer docs site to my localhost registry
* But pushing the developer docs to ghcr fails with 401 Unauthorized

I did wonder if it could be a size issue, as it takes a long time to upload, but the developer docs package looks to be about 35MB, which doesn't seem unreasonable.  And of course it would be very rude to report that as "authentication required" anyway.

@radu-matei, I think you probably know more about OCI than the rest of us - any insight into what might cause this behaviour and response, or how to diagnose it?

**Comment by vdice** [comment]
Superseded by https://github.com/fermyon/developer/pull/588

**Pull request closed without merging**
