### PR TITLE
Fix typo in template authoring page

### PR DESCRIPTION
**Pull request by quyumkehinde**

### CODE REVIEW

**Review by tpmccallum — APPROVED** [review]
Thanks @quyumkehinde

**Comment by tpmccallum** [comment]
@quyumkehinde if you need to know about signing, please see the documentation here:
https://developer.fermyon.com/spin/v2/contributing-docs#9-commit-changes

**Comment by quyumkehinde** [comment]
> @quyumkehinde if you need to know about signing, please see the documentation here: https://developer.fermyon.com/spin/v2/contributing-docs#9-commit-changes

Thank you for the reference @tpmccallum.

**Comment by quyumkehinde** [comment]
> @quyumkehinde Could you signoff and GPG-sign the commit please? These signatures are required for DCO and verification respectively. Thanks!

@itowlson I've signed off the commit now. Thank you for the note.

**Pull request merged**
