### PR TITLE
Migrate Bartholomew documentation

### LINKED ISSUE #183: Add Bartholomew docs to developer.fermyon.com

### PR DESCRIPTION
**Pull request by radu-matei**
close #183 
ref https://github.com/fermyon/bartholomew/pull/148

This commit migrates the Bartholomew documentation from its standalone website to the Fermyon Developer Home website.

I updated:

- the navigation bar to include Bartholomew
- the main and sidebar templates for Bartholomew
- the search functionality to include Bartholomew docs

Signed-off-by: Radu Matei <radu.matei@fermyon.com>

### CODE REVIEW

**Comment by flynnduism** [comment]
Testing this locally, the menus, search and docs pages are all working great - thanks @radu-matei!

I noticed some urls pointing at bartholomew.fermyon.dev, added an update to make those relative.
The developer homepage layout was too narrow as well, so I tweaked that.

**Review by flynnduism — APPROVED** [review]

**Comment by karthik2804** [comment]
We should also probably set up redirects on the `bartholomew.fermyon.dev` in the same manner as we have done for `spin`.

**Comment by radu-matei** [comment]
Fixed the broken links and added the missing images from the Bartholomew static assets.
Looking at redirects now.

**Comment by flynnduism** [comment]
@radu-matei this looks ready to go, there are two conflicts that need resolution

A fresh run of `npm run spin` and `npm run styles` should overwrite those to move forward.

**Comment by tpmccallum** [comment]
Thanks so much for this @radu-matei 
Thanks @flynnduism for your input also
Thanks @karthik2804 for your help tonight getting this rebased and updating some extras. Really appreciate it.
Please see new PR which replaces this one (a few extras in there)
https://github.com/fermyon/developer/pull/267

**Pull request closed without merging**
