### PR TITLE
Allow all code in code block to be seen by user

### PR DESCRIPTION
**Pull request by tpmccallum**
Signed-off-by: tpmccallum tim.mccallum@fermyon.com

### CODE REVIEW

**Comment by tpmccallum** [comment]
This change allows a user to see the entire codeblock i.e. which version of Spin they are actually installing. Refers to @Mikkels GH issue https://github.com/fermyon/developer/issues/253 entitled "Code snippet is cut due to limited width"

Please see silent video below for demo.


https://user-images.githubusercontent.com/9831342/219229926-e67e70d6-f57f-4b5a-aeee-a3f14c157e72.mp4

**Comment by karthik2804** [comment]
`styles.css` is a generated file. We would want to make all the CSS edits in the `styles.scss` file. Changes in `styles.css` will get overwritten the next time styles are regenerated. As far as the styling change, I will defer to @flynnduism.

**Comment by tpmccallum** [comment]
Ah, I see, happy to be guided by @flynnduism 
Please let me know if there is anything y'all need me to do/test.

**Comment by tpmccallum** [comment]
Thanks @karthik2804 
I have closed this and there is a new PR which updates the `scss`
https://github.com/fermyon/developer/pull/347
Any feedback welcome @flynnduism 
Thanks so much.

**Pull request closed without merging**
