### PR TITLE
Add TS example of handling POST data from a router.

### PR DESCRIPTION
**Pull request by technosophos**
Content must go through a pre-merge checklist.

## Pre-Merge Content Checklist

This documentation has been checked to ensure that:

- [x] The `title, `template`, and `date` are all set
- [ ] Does this PR have a new menu item (anywhere in `templates/*.hbs` files) that points to a document `.md` that is set to publish in the future? If so please only publish the `.md` and `.hbs` changes in real-time (otherwise there will be a menu item pointing to a `.md` file that does not exist)
- [x] File does not use CRLF, but uses plain LF (hint: use `cat -ve <filename> | grep '^M' | wc -l` and expect 0 as a result) 
- [x] Has passed [`bart check`](https://developer.fermyon.com/bartholomew/quickstart)
- [ ] Has been manually tested by running in Spin/Bartholomew (hint: use `PREVIEW_MODE=1` and run `npm run styles` to update styling)
- [x] Headings are using Title Case
- [x] Code blocks have the programming language set to properly highlight syntax and the proper copy directive
- [x] Have tested with `npm run test` and resolved all errors
- [ ] Relates to an existing (potentially outdated) blog article? If so please add URL in blog to point to this content.

### CODE REVIEW

**Comment by technosophos** [comment]
Huge thanks to @bacongobbler for finding a couple of potential fixes.

**Review by itowlson — APPROVED** [review]

**Comment by karthik2804** [comment]
@technosophos this looks great. Out of curiosity, would it be better if we add an example of using the router with the `spin-component-route` along with it and make it a more general example of the usage of the router?

**Comment by technosophos** [comment]
@karthik2804 Yeah, that is a good idea. Let me add that.

**Comment by technosophos** [comment]
Okay, @karthik2804 -- updated in both

**Pull request merged**
