### PR TITLE
Fixed links to examples - finished - tests passing

### PR DESCRIPTION
**Pull request by tpmccallum**
Original broken list is:

```
https://github.com/fermyon/spin/tree/main/examples/redis-rust
https://github.com/fermyon/spin/tree/main/examples/http-rust-router
https://github.com/fermyon/spin/tree/main/examples/rust-outbound-redis
https://github.com/fermyon/spin/tree/main/examples/tinygo-outbound-redis
https://github.com/fermyon/spin/blob/main/examples/wasi-http-rust-streaming-outgoing-body/src/lib.rs
https://github.com/fermyon/spin/tree/main/examples/http-tinygo-outbound-http
https://github.com/fermyon/spin/tree/main/examples/rust-outbound-redis
https://github.com/fermyon/spin/tree/main/examples/tinygo-outbound-redis
https://github.com/fermyon/spin/tree/main/examples/rust-outbound-mysql
https://github.com/fermyon/spin/tree/main/examples/rust-outbound-pg
https://github.com/fermyon/spin/tree/main/examples/redis-rust
https://github.com/fermyon/spin/tree/main/examples/rust-outbound-redis
https://github.com/fermyon/spin/tree/main/examples/tinygo-outbound-redis
https://github.com/fermyon/spin/tree/main/examples/http-rust-outbound-http
https://github.com/fermyon/spin/tree/main/examples/http-tinygo-outbound-http
https://github.com/fermyon/spin/tree/main/examples/rust-outbound-redis
https://github.com/fermyon/spin/tree/main/examples/tinygo-outbound-redis
https://github.com/fermyon/spin/tree/main/examples/rust-outbound-mysql
https://github.com/fermyon/spin/tree/main/examples/rust-outbound-pg
```

Fixes https://github.com/fermyon/developer/issues/1181

### CODE REVIEW

**Review by vdice — APPROVED** [review]
LGTM, though do note a follow-up will be required for the rust examples depending on timing with https://github.com/fermyon/spin-rust-sdk/pull/9.  Not sure if you'd like to wait for that to land or not...

**Comment by vdice** [comment]
@tpmccallum I also just noticed the changes to package-lock.json and spin-up-hub/package-lock.json.  Intentional?

**Comment by tpmccallum** [comment]
Thanks so much @vdice 
I will merge this one for now, so that other developer PR tests pass (while we wait for that other #9 to be approved)
When #9 is approved I will create a new PR and resolve the new URLs
Thanks again.

**Comment by tpmccallum** [comment]
I think the package-lock.json and spin-up-hub/package-lock.json are updated when I do the following:

```bash
cd developer
cd spin-up-hub
npm install
cd ../
npm install
npm run test
spin build
spin up -e PREVIEW_MODE=1
```

The above is my go-to routine to build, test and run everything locally. Not sure if committing those `.json` files is necessary. Perhaps @karthik2804 has some ideas about if we can exclude them from the versioning?

**Comment by karthik2804** [comment]
Using `npm ci` instead of `npm install` should make sure no packages are updated. The default behaviour of `npm install` is to bump versions.

**Pull request merged**
